apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://22FDA4B5BA0F03A4A3C9C04ACF468E3F.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:971882029798:cluster/DILWL-Campus_Cluster
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:971882029798:cluster/DILWL-Campus_Cluster
    user: arn:aws:eks:us-east-1:971882029798:cluster/DILWL-Campus_Cluster
  name: arn:aws:eks:us-east-1:971882029798:cluster/DILWL-Campus_Cluster
current-context: arn:aws:eks:us-east-1:971882029798:cluster/DILWL-Campus_Cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:971882029798:cluster/DILWL-Campus_Cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - DILWL-Campus_Cluster
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
