"""Fix history tracking

Revision ID: 2c29c08483d1
Revises: 33818718aafd
Create Date: 2025-04-18 19:05:31.706437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c29c08483d1'
down_revision = '33818718aafd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.create_index('idx_history_post_timestamp', ['post_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_history_user_timestamp', ['user_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_index('idx_history_user_timestamp')
        batch_op.drop_index('idx_history_post_timestamp')

    # ### end Alembic commands ###
