"""Add replies_count field to Post

Revision ID: 801f80530c67
Revises: 74641ae6fa17
Create Date: 2025-04-18 17:36:13.130872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801f80530c67'
down_revision = '74641ae6fa17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replies_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('replies_count')

    # ### end Alembic commands ###
