"""Add category_id to Post

Revision ID: a7be573bfa78
Revises: 65eef4a6ef8c
Create Date: 2025-04-20 15:35:04.409237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7be573bfa78'
down_revision = '65eef4a6ef8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_block',
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    )
    op.create_table('user_follow',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_message_read_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profile_username'), ['username'], unique=True)

    op.create_table('user_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_bookmark',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('post_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('post_vote',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.drop_table('bookmarks')
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_index('idx_history_post_timestamp')
        batch_op.drop_index('idx_history_user_timestamp')

    op.drop_table('history')
    op.drop_table('blocked_users')
    op.drop_table('votes')
    op.drop_table('followers')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])
        batch_op.drop_column('likes')
        batch_op.drop_column('dislikes')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('last_message_read_time')
        batch_op.drop_column('username')
        batch_op.drop_column('gender')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_message_read_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_user_username', ['username'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    op.create_table('followers',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name='followers_followed_id_fkey'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='followers_follower_id_fkey')
    )
    op.create_table('votes',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vote_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='votes_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='votes_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name='votes_pkey')
    )
    op.create_table('blocked_users',
    sa.Column('blocker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('blocked_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['user.id'], name='blocked_users_blocked_id_fkey'),
    sa.ForeignKeyConstraint(['blocker_id'], ['user.id'], name='blocked_users_blocker_id_fkey'),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id', name='blocked_users_pkey')
    )
    op.create_table('history',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='history_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='history_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name='history_pkey')
    )
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.create_index('idx_history_user_timestamp', ['user_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_history_post_timestamp', ['post_id', 'timestamp'], unique=False)

    op.create_table('bookmarks',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='bookmarks_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='bookmarks_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name='bookmarks_pkey')
    )
    op.drop_table('post_vote')
    op.drop_table('post_history')
    op.drop_table('post_bookmark')
    op.drop_table('comment')
    op.drop_table('user_setting')
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profile_username'))

    op.drop_table('user_profile')
    op.drop_table('user_follow')
    op.drop_table('user_block')
    op.drop_table('category')
    # ### end Alembic commands ###
