"""fix message relationships

Revision ID: f3bc2ececcbc
Revises: a7be573bfa78
Create Date: 2025-04-20 18:06:30.898795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3bc2ececcbc'
down_revision = 'a7be573bfa78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_notification_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_name'))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
